server:
  port: 6000

spring:
  application:
    name: gateway-center
  cloud:
    gateway:
      routes:
        - id: rateLimit_route
          uri: http://localhost:6001
          order: 0
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallback
                fallbackUri:forward:/fallback
  hystrix.command.fallback.execution.isolation.thread.timeoutInMilliseconds: 5000
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: *
    web:
      exposure:
        include: *